namespace DatabaseDeletor.Domain.Tests.Entities;

using DatabaseDeletor.Domain.Entities;
using DatabaseDeletor.Domain.Enums;

public sealed class DeletionPlanTests
{
    [Fact]
    public void TotalEstimatedRows_SumsAllStepEstimates()
    {
        var plan = new DeletionPlan
        {
            RootTable = new TableInfo { Schema = "dbo", Name = "Users" },
            WhereClause = null,
            Steps =
            [
                new DeletionStep { Order = 0, Table = new TableInfo { Schema = "dbo", Name = "Orders" }, DeleteSql = "DELETE FROM Orders", EstimatedRowCount = 100 },
                new DeletionStep { Order = 1, Table = new TableInfo { Schema = "dbo", Name = "Users" }, DeleteSql = "DELETE FROM Users", EstimatedRowCount = 50 }
            ]
        };

        plan.TotalEstimatedRows.Should().Be(150);
    }

    [Fact]
    public void Status_DefaultsTo_PlanGenerated()
    {
        var plan = new DeletionPlan
        {
            RootTable = new TableInfo { Schema = "dbo", Name = "Users" },
            WhereClause = null,
            Steps = []
        };

        plan.Status.Should().Be(DeletionStatus.PlanGenerated);
    }

    [Fact]
    public void Id_IsAutoGenerated_NotEmpty()
    {
        var plan = new DeletionPlan
        {
            RootTable = new TableInfo { Schema = "dbo", Name = "Users" },
            WhereClause = null,
            Steps = []
        };

        plan.Id.Should().NotBeEmpty();
    }

    [Fact]
    public void CreatedAt_IsUtcNow()
    {
        var before = DateTime.UtcNow;

        var plan = new DeletionPlan
        {
            RootTable = new TableInfo { Schema = "dbo", Name = "Users" },
            WhereClause = null,
            Steps = []
        };

        var after = DateTime.UtcNow;

        plan.CreatedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }
}

public sealed class DeletionReportTests
{
    private static TableInfo TestTable => new() { Schema = "dbo", Name = "Users" };

    [Fact]
    public void TotalDeletedRows_SumsAllResults()
    {
        var report = new DeletionReport
        {
            RootTable = TestTable,
            Results =
            [
                new DeletionStepResult { Table = TestTable, DeletedCount = 100, Duration = TimeSpan.FromSeconds(1) },
                new DeletionStepResult { Table = new TableInfo { Schema = "dbo", Name = "Orders" }, DeletedCount = 200, Duration = TimeSpan.FromSeconds(2) }
            ],
            StartedAt = DateTime.UtcNow.AddSeconds(-3),
            CompletedAt = DateTime.UtcNow
        };

        report.TotalDeletedRows.Should().Be(300);
    }

    [Fact]
    public void TotalDuration_ReturnsTimeDifference()
    {
        var start = new DateTime(2024, 1, 1, 12, 0, 0, DateTimeKind.Utc);
        var end = new DateTime(2024, 1, 1, 12, 0, 10, DateTimeKind.Utc);

        var report = new DeletionReport
        {
            RootTable = TestTable,
            Results = [],
            StartedAt = start,
            CompletedAt = end
        };

        report.TotalDuration.Should().Be(TimeSpan.FromSeconds(10));
    }

    [Fact]
    public void HasErrors_NoErrors_ReturnsFalse()
    {
        var report = new DeletionReport
        {
            RootTable = TestTable,
            Results =
            [
                new DeletionStepResult { Table = TestTable, DeletedCount = 100, Duration = TimeSpan.FromSeconds(1) }
            ],
            StartedAt = DateTime.UtcNow,
            CompletedAt = DateTime.UtcNow
        };

        report.HasErrors.Should().BeFalse();
    }

    [Fact]
    public void HasErrors_WithErrors_ReturnsTrue()
    {
        var report = new DeletionReport
        {
            RootTable = TestTable,
            Results =
            [
                new DeletionStepResult { Table = TestTable, DeletedCount = 0, Duration = TimeSpan.FromSeconds(1), ErrorMessage = "FK violation" }
            ],
            StartedAt = DateTime.UtcNow,
            CompletedAt = DateTime.UtcNow
        };

        report.HasErrors.Should().BeTrue();
    }
}

public sealed class DeletionStepResultTests
{
    [Fact]
    public void Success_NoError_ReturnsTrue()
    {
        var result = new DeletionStepResult
        {
            Table = new TableInfo { Schema = "dbo", Name = "Users" },
            DeletedCount = 100,
            Duration = TimeSpan.FromSeconds(1)
        };

        result.Success.Should().BeTrue();
    }

    [Fact]
    public void Success_WithError_ReturnsFalse()
    {
        var result = new DeletionStepResult
        {
            Table = new TableInfo { Schema = "dbo", Name = "Users" },
            DeletedCount = 0,
            Duration = TimeSpan.FromSeconds(1),
            ErrorMessage = "Something went wrong"
        };

        result.Success.Should().BeFalse();
    }
}

public sealed class DeletionProgressTests
{
    [Fact]
    public void OverallPercentage_CalculatesCorrectly()
    {
        var progress = new DeletionProgress
        {
            CurrentStep = 1,
            TotalSteps = 2,
            CurrentTable = new TableInfo { Schema = "dbo", Name = "Users" },
            DeletedRowsInStep = 50,
            EstimatedRowsInStep = 100,
            TotalDeletedRows = 250,
            TotalEstimatedRows = 500
        };

        progress.OverallPercentage.Should().Be(50.0);
    }

    [Fact]
    public void OverallPercentage_ZeroEstimated_ReturnsZero()
    {
        var progress = new DeletionProgress
        {
            CurrentStep = 1,
            TotalSteps = 1,
            CurrentTable = new TableInfo { Schema = "dbo", Name = "Users" },
            DeletedRowsInStep = 0,
            EstimatedRowsInStep = 0,
            TotalDeletedRows = 0,
            TotalEstimatedRows = 0
        };

        progress.OverallPercentage.Should().Be(0.0);
    }
}
