#!/usr/bin/env zsh
set -Eeuo pipefail
IFS=$'\n\t'
# _publishNuget.sh
# Publishes NuGet packages to nuget.org with validation
# Requires NUGET_API_KEY environment variable

# Detect script directory (cross-compatible way)
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [[ -n "${(%):-%x}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
else
  SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

# Load common functions if available
if [[ -f "$SCRIPT_DIR/_common.sh" ]]; then
    source "$SCRIPT_DIR/_common.sh"
else
    # Minimal fallback logging functions
    info() { echo -e "\033[34m[INFO]\033[0m $*"; }
    error() { echo -e "\033[31m[ERROR]\033[0m $*" >&2; }
    success() { echo -e "\033[32m[SUCCESS]\033[0m $*"; }
fi

PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Configuration
NUGET_SOURCE="https://api.nuget.org/v3/index.json"
OUTPUT_DIR="$PROJECT_ROOT/DEPLOYMENT/nuget"
PACKAGE_VERSION=""

# Parse arguments
DRY_RUN=false
for arg in "$@"; do
    if [[ "$arg" == "--dry-run" ]]; then
        DRY_RUN=true
    fi
done

echo "========================================"
echo "NuGet Publish Script"
echo "Target: nuget.org"
echo "========================================"

# Resolve API Key (Env Var or File)
resolve_api_key() {
    if [[ -n "${NUGET_API_KEY:-}" ]]; then
        return 0
    fi
    
    # Check current directory and project root for key file
    local key_file=".nuget-api-key"
    local key_value=""
    
    if [[ -f "$key_file" ]]; then
        key_value="$(cat "$key_file" | tr -d ' \t\r\n')"
    elif [[ -f "$PROJECT_ROOT/$key_file" ]]; then
        key_value="$(cat "$PROJECT_ROOT/$key_file" | tr -d ' \t\r\n')"
    fi
    
    if [[ -n "$key_value" ]]; then
        export NUGET_API_KEY="$key_value"
        info "Loaded NUGET_API_KEY from file."
        return 0
    fi
    
    return 1
}

resolve_api_key

# Check for NUGET_API_KEY if not dry run
if [[ "$DRY_RUN" == "false" ]] && [[ -z "${NUGET_API_KEY:-}" ]]; then
    error "NUGET_API_KEY environment variable is not set and .nuget-api-key file not found!"
    error "Option A: export NUGET_API_KEY=\"your-key\""
    error "Option B: echo \"your-key\" > .nuget-api-key"
    exit 1
elif [[ "$DRY_RUN" == "true" ]] && [[ -z "${NUGET_API_KEY:-}" ]]; then
    info "NUGET_API_KEY not set, but running in DRY RUN mode."
fi

# Detect project information (simplified check)
if [[ ! -f "$PROJECT_ROOT/Versioner.sln" ]] && [[ -z "$(find "$PROJECT_ROOT" -maxdepth 2 -name "*.csproj" -type f)" ]]; then
    error "No .NET project found in project root"
    exit 1
fi

# Determine version
if [[ -f "$PROJECT_ROOT/version.txt" ]]; then
    PACKAGE_VERSION="$(cat "$PROJECT_ROOT/version.txt" | tr -d ' \t\r\n')"
    info "Version from version.txt: $PACKAGE_VERSION"
else
    # Try to find version in first csproj
    CSPROJ_FILE="$(find "$PROJECT_ROOT" -name "*.csproj" -not -path "*Test*" -print -quit)"
    if [[ -n "$CSPROJ_FILE" ]]; then
        PACKAGE_VERSION="$(grep -o "<Version>[^<]*</Version>" "$CSPROJ_FILE" | sed 's/<Version>//' | sed 's/<\/Version>//' | tr -d ' \t\r\n')"
        info "Version from $(basename "$CSPROJ_FILE"): $PACKAGE_VERSION"
    fi
fi

if [[ -z "$PACKAGE_VERSION" ]]; then
    error "Could not determine package version! Create version.txt or set <Version> in csproj."
    exit 1
fi

# Prepare output directory
info "Preparing output directory: $OUTPUT_DIR"
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Find projects to pack (exclude tests and examples)
CSPROJ_FILES=()
while IFS= read -r -d '' file; do
    if [[ "$file" != *"Tests"* ]] && [[ "$file" != *"Test"* ]] && [[ "$file" != *"ExampleFiles"* ]]; then
        CSPROJ_FILES+=("$file")
    fi
done < <(find "$PROJECT_ROOT" -name "*.csproj" -print0)

if [[ ${#CSPROJ_FILES[@]} -eq 0 ]]; then
    error "No valid projects found to pack."
    exit 1
fi

info "Projects to publish: ${#CSPROJ_FILES[@]}"

# 1. Pack
echo "========== PACKING =========="

# Cleanup function for temporary files
cleanup() {
    if [[ -f "$PROJECT_ROOT/Directory.Build.props.tmp_nuget" ]]; then
        rm "$PROJECT_ROOT/Directory.Build.props.tmp_nuget"
    fi
    if [[ -f "$PROJECT_ROOT/Directory.Build.props" ]] && [[ -f "$PROJECT_ROOT/Directory.Build.props.bak_nuget" ]]; then
         mv "$PROJECT_ROOT/Directory.Build.props.bak_nuget" "$PROJECT_ROOT/Directory.Build.props"
    elif [[ -f "$PROJECT_ROOT/Directory.Build.props" ]] && grep -q "Generated by _publishNuget.sh" "$PROJECT_ROOT/Directory.Build.props"; then
         rm "$PROJECT_ROOT/Directory.Build.props"
    fi
}
trap cleanup EXIT

# Check if README.md exists and verify logic for including it
if [[ -f "$PROJECT_ROOT/README.md" ]]; then
    info "Found README.md in project root."
    
    # Check if Directory.Build.props exists
    if [[ -f "$PROJECT_ROOT/Directory.Build.props" ]]; then
        info "Directory.Build.props already exists. Assuming it handles README.md or user manages it."
    else
        info "Creating temporary Directory.Build.props to include README.md..."
        cat > "$PROJECT_ROOT/Directory.Build.props" <<EOF
<Project>
  <!-- Generated by _publishNuget.sh to include README.md -->
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$PROJECT_ROOT/README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
EOF
    fi
fi

for csproj in "${CSPROJ_FILES[@]}"; do
    project_name="$(basename "$csproj" .csproj)"
    info "Packing $project_name..."
    
    # Pack with symbols and source
    # Important: Ensure version is passed
    if ! dotnet pack "$csproj" \
        --configuration Release \
        --output "$OUTPUT_DIR" \
        --include-symbols \
        --include-source \
        -p:PackageVersion="$PACKAGE_VERSION" \
        -p:Version="$PACKAGE_VERSION" \
        --verbosity minimal; then
        
        error "Failed to pack $project_name"
        exit 1
    fi
done

# 2. Validate Artifacts
echo "========== VALIDATING ARTIFACTS =========="
PACKAGES_FOUND=0
for nupkg in "$OUTPUT_DIR"/*.nupkg; do
    [[ -e "$nupkg" ]] || continue
    # Skip symbols packages for main validation logic if needed, but checking them is fine too
    if [[ "$nupkg" == *".symbols.nupkg" ]]; then
        continue
    fi
    PACKAGES_FOUND=$((PACKAGES_FOUND+1))
    
    filename=$(basename "$nupkg")
    info "Validating $filename..."

    # Check validity of filename version
    if [[ "$filename" != *"$PACKAGE_VERSION"* ]]; then
        error "Filename $filename does not fulfill versioning requirement: $PACKAGE_VERSION"
        exit 1
    fi

    # Check for README using unzip (listing content)
    # Check if unzip is available
    if command -v unzip >/dev/null 2>&1; then
        # Look for README.md (case insensitive check usually good, often stuck to lower case)
        # Use grep without -q to ensure all input is consumed, preventing SIGPIPE on unzip
        # which would cause failure with set -o pipefail
        if unzip -l "$nupkg" | grep -i "README.md" > /dev/null; then
            success "  - README.md found in package"
        else
            error "README.md NOT found in $filename"
            exit 1
        fi
    else
        error "unzip command not found, cannot validate package contents."
        exit 1
    fi
done

if [[ $PACKAGES_FOUND -eq 0 ]]; then
    error "No packages created in $OUTPUT_DIR"
    exit 1
fi

success "Artifacts validation passed."

# 3. Push to NuGet
echo "========== PUSHING TO NUGET =========="
for nupkg in "$OUTPUT_DIR"/*.nupkg; do
    [[ -e "$nupkg" ]] || continue
    if [[ "$nupkg" == *".symbols.nupkg" ]]; then
        continue
    fi
    
    filename=$(basename "$nupkg")
    
    if [[ "$DRY_RUN" == "true" ]]; then
        info "[DRY RUN] Would push $filename to $NUGET_SOURCE"
    else
        info "Pushing $filename..."
        if ! dotnet nuget push "$nupkg" \
            --source "$NUGET_SOURCE" \
            --api-key "$NUGET_API_KEY" \
            --skip-duplicate; then
            
            error "Failed to push $filename"
            exit 1
        fi
        
        # Determine Package ID from filename
        # Naive approach: remove .$PACKAGE_VERSION.nupkg
        # Example: MyLib.1.0.0.nupkg -> MyLib
        PACKAGE_ID="${filename%"$PACKAGE_VERSION.nupkg"}"
        PACKAGE_ID="${PACKAGE_ID%.}" # Remove trailing dot if exists
        
        success "Package published successfully."
        echo "Link: https://www.nuget.org/packages/$PACKAGE_ID/$PACKAGE_VERSION"
    fi
done

echo "========================================"
if [[ "$DRY_RUN" == "true" ]]; then
    echo "NuGet Publish DRY RUN Completed Successfully!"
else
    echo "NuGet Publish Completed Successfully!"
fi
echo "========================================"
